{% set name = "optimade" %}
{% set version = "0.20.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimade-{{ version }}.tar.gz
  sha256: f253ab2726c1f0bfd9b5fe1d2f69f9b133bc3060d4e1bab0458689c3242b7a52

build:
  number: 0
  noarch: python
  entry_points:
    - optimade-validator=optimade.validator:validate
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - email_validator >=1.2,<1.3
    - lark >=1.1,<1.2
    - pydantic >=1.10.2,<1.11
    - python >=3.8
    - requests >=2.28,<2.29

test:
  imports:
    - optimade
    - optimade.adapters
  commands:
    - pip check
    - optimade-validator --help
  requires:
    - pip

about:
  home: http://www.optimade.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for implementing and consuming OPTIMADE APIs.
  description: |
    The aim of OPTIMADE is to develop a common API, compliant with the
    JSON API 1.0 specification. This is to enable interoperability among
    databases that contain calculated properties of existing and
    hypothetical materials.
  doc_url: https://www.optimade.org/optimade-python-tools/
  dev_url: https://github.com/Materials-Consortia/optimade-python-tools

extra:
  recipe-maintainers:
    - jan-janssen
    - ml-evs
