{% set name = "optimade" %}
{% set version = "0.12.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimade-{{ version }}.tar.gz
  sha256: 869ef97042349957f11cf003d934182c93353797056923fefc2b3c67f6d8e0ef

build:
  number: 0
  noarch: python
  entry_points:
    - optimade-validator=optimade.validator:validate
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - email_validator >=1.1,<1.2
    - fastapi >=0.61.1,<0.62
    - lark-parser >=0.10.1,<0.11
    - pydantic >=1.6.1,<1.7
    - python >=3.5
    - requests >=2.24,<2.25
    - typing-extensions >=3.7,<3.8

test:
  imports:
    - optimade
    - optimade.adapters
  commands:
    - pip check
    - optimade-validator --help
  requires:
    - pip

about:
  home: http://www.optimade.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for implementing and consuming OPTIMADE APIs.
  description: |
    The aim of OPTIMADE is to develop a common API, compliant with the
    JSON API 1.0 specification. This is to enable interoperability among
    databases that contain calculated properties of existing and 
    hypothetical materials.
  doc_url: https://www.optimade.org/optimade-python-tools/
  dev_url: https://github.com/Materials-Consortia/optimade-python-tools

extra:
  recipe-maintainers:
    - jan-janssen
    - ml-evs
